name: Update requirements.txt file

on:
  push:
    branches: [ main, staging, test]
jobs:
  update:
    if: ${{ !github.event.act }} # skip during local actions testing
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install poetry
        shell: bash
        run: |
          PIP_BREAK_SYSTEM_PACKAGES=1 pip install poetry --user
          poetry self add poetry-plugin-export

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          check-latest: true
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Export requirements.txt
        shell: bash
        run: |
          poetry export --format requirements.txt --output requirements.txt

      - name: Commit changes if any
        # Skip this step if being run by nektos/act
        if: ${{ !env.ACT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git pull -f
            git add requirements.txt
            git commit -m "ci: Update requirements.txt" -a
            git push
          fi
