name: Main CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    name: "Lint & Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Environment"
        uses: ./.github/workflows/reusable-setup.yml
        with:
          python-version: '3.12'

      - name: Check formatting with Ruff Formatter
        run: uvx ruff format . --check

      - name: Check import sorting with Ruff
        run: uvx ruff check --select I .

  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12']
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Environment"
        uses: ./.github/workflows/reusable-setup.yml
        with:
          python-version: ${{ matrix.python-version }}

      - name: See if any parser changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'cape_parsers/CAPE/core/*.py'
              - 'cape_parsers/CAPE/community/**.py'

      # CORRECTED: Use 'poetry run'
      - name: Test parsers only if any parser changed
        if: steps.changes.outputs.src == 'true'
        run: |
          poetry run python -m pytest tests_parsers -s --import-mode=append
