name: Python package

env:
  COLUMNS: 132

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # IMPORTANT: This fetches all history and tags

      - name: Checkout test files repo
        uses: actions/checkout@v4
        with:
          repository: CAPESandbox/CAPE-TestFiles
          path: tests/data/

      - uses: ./.github/actions/python-setup/
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Ruff
        run: poetry run ruff check . --line-length 132 --ignore E501,E402

      - name: See if any parser changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'cape_parsers/CAPE/core/*.py'
              - 'cape_parsers/CAPE/community/**.py'

      - name: Test parsers only if any parser changed
        if: steps.changes.outputs.src == 'true'
        run: |
          sudo apt-get install yara
          poetry run pip install yara-python
          poetry run python -m pytest tests_parsers -s --import-mode=append

      # setuptools-scm runs here automatically and sets the version
      # from the Git tag associated with the release.

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.10"]
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up python
        uses: ./.github/actions/python-setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Format with black
        run: uv run ruff format .

      - name: Format imports with ruff isort
        run: uv run ruff check --select I --fix .

      - name: Commit changes if any
        # Skip this step if being run by nektos/act
        if: ${{ !env.ACT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m "style: Automatic code formatting" -a
            git push
          fi
