name: Reusable Python and UV Setup

# CRITICAL: This makes the workflow "reusable"
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  # The single job inside the reusable workflow
  setup-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - uses: actions/cache@v4
        id: cache-uv-venv
        with:
          path: .venv
          key: ${{ runner.os }}-python-${{ inputs.python-version }}-uv-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ inputs.python-version }}-uv-
      - if: steps.cache-uv-venv.outputs.cache-hit != 'true'
        run: |
          uv venv --python ${{ inputs.python-version }}
          uv pip sync --all-extras pyproject.toml
