name: YARA tests

on:
  schedule:
  - cron: '0 8 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

        with:
          repository: CAPESandbox/CAPE-TestFiles
          path: tests/data/

      - uses: ./.github/workflows/reusable-setup.yml
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        run: uvx pytest tests/test_yara.py -s --import-mode=append
